### ISSUE TITLE
What is the difference between automation config vs normal config

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#85]
@abelsonlive, 

[Automation config](https://github.com/newslynx/automation/blob/master/config.yaml.sample)
[Core config](https://github.com/newslynx/newslynx-core/blob/master/newslynx/dot_newslynx/config.yaml)

Automation doesn't have `sqlalchemy_database_uri` for instance.

When using Automation, what do the file paths for defaults correspond to? If the user wants to use our default tag and recipes in https://github.com/newslynx/newslynx-core/tree/master/newslynx/dot_newslynx/defaults, what do they do during the automation and installation phase? 

```
# Filepaths to default recipes + tags to add for each
# new organization.
default_recipes: ~/.newslynx/defaults/recipes.yaml
default_tags: ~/.newslynx/defaults/tags.yaml
```

**Comment by mhkeller** [comment]
It appears that `newslynx init` during automation doesn't do `--app-defaults`? https://github.com/newslynx/automation/blob/master/provisioning/newslynx-core.yaml#L69

**Comment by abelsonlive** [comment]
It was because these things were done at different times. I'll remove the defaults from automation and use `--app-defaults`. The canonical place for the App's defaults will then be: https://github.com/newslynx/newslynx-core/tree/master/newslynx/dot_newslynx/defaults.

**Comment by mhkeller** [comment]
They should still be able to overwrite the config values when using automation, tho right? Like, their Google App and Twitter app keys for instance. Or, if someone wants to specify their own default tags when running automation, could they still enter the path to local `tags.yaml`?

**Comment by mhkeller** [comment]
By "they" i mean users

**Comment by mhkeller** [comment]
These values seem like what users would want to configure each time. And if they include these values in `config.yaml` within automation they overwrite what is in `dot_newslynx`. or is there a better workflow?

``` yaml
secret_key: changeme
app_secret_key: changemetoo
super_user: admin
super_user_email: changeme@example.com
super_user_password: admin
super_user_apikey: mj
super_user_org: 'admin'
super_user_timezone: UTC

# The Database URI (This is mandatory!)
sqlalchemy_database_uri: postgres://localhost:5432/newslynx

# Filepaths to default recipes + tags to add for each
# new organization.
default_recipes: ~/.newslynx/defaults/recipes.yaml
default_tags: ~/.newslynx/defaults/tags.yaml

# # Twitter
# twitter_api_key: dsfadfad
# twitter_api_secret: 3824-3482-341234

# # Google Analytics
# google_analytics_client_id: sdfasdfsafd
# google_analytics_client_secret: o34823-4-23234

# # Facebook
# facebook_app_id: 24123413412
# facebook_app_secret: lajd38opru2j
```
